/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChocolateFactoryTest;

import ChocolateFactory.BouilleurChocolat;
import org.junit.Test;
import static org.junit.Assert.*;

public class BouilleurChocolatTest {

    @Test
    public void aNewBouilleurChocolatisEmpty() {
        BouilleurChocolat classUnderTest = BouilleurChocolat.getInstance();
        assertTrue("A new BouilleurChocolat is empty", classUnderTest.estVide());
    }

    @Test
    public void twoChocolateBoilersMightBlowTheFactory() {
        BouilleurChocolat c1 = BouilleurChocolat.getInstance();
        BouilleurChocolat c2 = BouilleurChocolat.getInstance();

        String result;
        result = c1.remplir() + "/" + c1.bouillir() + "/" + c2.remplir();
        String unExpected = "Remplissage/Bout/Remplissage";
        assertFalse(unExpected.equals(result));
    }
}
